cleanup: delete demo probes
preludeorg/libraries pull request #948
Opened 2024-02-01 16:52 UTC by makk94

2024-02-01 19:36 UTC, packplusplus requested changes
Github actions reference the demo scripts in multiple places: https://github.com/preludeorg/libraries/blob/master/.github/actions/shell_probes/action.yml

2024-03-05 15:42 UTC, makk94 commented
updated the actions

2024-03-05 17:47 UTC, keitharobertson approved these changes

2024-03-05 18:44 UTC, packplusplus approved these changes
LGTM!

2024-03-05 18:46 UTC, merged